
FROM rust AS base
LABEL maintainer="Juncheng"
LABEL version="0.0.2"


WORKDIR /

# install dependency
# RUN apt update && apt-get install -yqq libglib2.0-dev libgoogle-perftools-dev cmake git sudo wget gcc g++ xxhash
RUN apt update && apt-get install -yqq cmake git sudo wget

# copy local repo instead of cloning
COPY . /libCacheSim/

# build libCacheSim
WORKDIR /libCacheSim/
# RUN mkdir _build;
RUN bash ./scripts/install_dependency.sh
RUN bash ./scripts/install_libcachesim.sh


WORKDIR /libCacheSim/_build/
RUN cmake -DSUPPORT_ZSTD_TRACE=on .. && make -j && sudo make install


WORKDIR /libCacheSim/_build/bin/

